data:
  n_pix: 224
  psize: 2.146
  submission:
    fname: data/dataset_2_ground_truth/submission_0.pt
    volume_key: volumes
    metadata_key: populations
    label_key: id
  ground_truth:
    volumes: data/dataset_2_ground_truth/maps_gt_flat.pt
    metadata: data/dataset_2_ground_truth/metadata.csv
  mask:
    do: true
    volume: data/dataset_2_ground_truth/mask_dilated_wide_224x224.mrc
analysis:
  metrics:
    - l2
    - corr
    - bioem
    - fsc
    - res
  chunk_size_submission: 80
  chunk_size_gt: 190
  normalize:
    do: true
    method: median_zscore
output: results/map_to_map_distance_matrix_submission_0.pkl