path_to_volumes: /path/to/volumes
box_size_ds: 32
submission_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
experiment_mode: "all_vs_ref" # options are "all_vs_all", "all_vs_ref"

# optional unless experiment_mode is "all_vs_ref"
reference_options:
  path_to_reference: /path/to/reference
  n_volumes: 300 # optional, default is all volumes
  random_subset: False # if False, the subset is chosen as volumes[::skip_vols, ...] to satisfy n_volumes

dtype: "float32" # options are "float32", "float64"
output_options:
  # path will be created if it does not exist
  output_path: /path/to/output
  # whether or not to save the processed volumes (downsampled, normalized, etc.)
  save_volumes: True
  # whether or not to save the SVD matrices (U, S, V)
  save_svd_matrices: True
