path_to_volumes: /path/to/volumes
box_size_ds: 32
submission_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
experiment_mode: "all_vs_ref" # options are "all_vs_all", "all_vs_ref"

power_spectrum_normalization:
  ref_vol_key: "Vanilla" # which submission should be used
  ref_vol_index: 0 # which volume of that submission should be used

# optional unless experiment_mode is "all_vs_ref"
path_to_reference: /path/to/reference
dtype: "float32" # options are "float32", "float64"
output_options:
  # path to file will be created if it does not exist
  output_file: /path/to/output_file.pt
  # whether or not to save the processed volumes (downsampled, normalized, etc.)
  save_volumes: False
  # whether or not to save the SVD matrices (U, S, V)
  save_svd_matrices: False
