# GHA workflow for running tests.
#
# Largely taken from
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# Please check the link for more detailed instructions

name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Cache test data
        id: cache_test_data
        uses: actions/cache@v3
        with:
          path: tests/data
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('**/tests/scripts/fetch_test_data.sh') }}

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: pyproject.toml  # this is optional

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[dev]
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
          
      - name: Get test data from OSF
        if: steps.cache_test_data.outputs.cache-hit != 'true'
        run: |
          sh tests/scripts/fetch_test_data.sh
          
      - name: Test with pytest
        run: |
          pytest tests/test_map_to_map.py
          pytest tests/test_distribution_to_distribution.py
