# GHA workflow for running tests.
#
# Largely taken from
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# Please check the link for more detailed instructions

name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]


    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Cache test data
        id: cache_test_data
        uses: actions/cache@v3
        with:
          path: |
            tests/data
            data
          key: venv-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('**/tests/scripts/fetch_test_data.sh') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest omegaconf
          
      - name: Get test data from OSF
        if: ${{ steps.cache_test_data.outputs.cache-hit != 'true' }}
        run: |
          sh tests/scripts/fetch_test_data.sh
          
      - name: Test with pytest
        run: |
          pytest tests/test_preprocessing.py
          pytest tests/test_svd.py
          pytest tests/test_map_to_map.py
          pytest tests/test_distribution_to_distribution.py
          
